### Créer un Todo (champs obligatoires)
POST http://localhost:8080/todos
Content-Type: application/json

{
  "title": "Nouvelle tâche",
  "completed": false
}

### Créer un Todo complet
POST http://localhost:8080/todos
Content-Type: application/json

{
  "title": "Nouvelle tâche",
  "completed": false
}

### Récupérer tous les Todos
GET http://localhost:8080/todos
Content-Type: application/json

### Récupérer un Todo par ID
GET http://localhost:8080/todos/1
Content-Type: application/json

### Supprimer un Todo par ID
DELETE http://localhost:8080/todos/1
Content-Type: application/json
